### ISSUE TITLE
Error instantiating ChartCustomElement

### ISSUE THREAD

**Issue by vincentleeuwen** [philiphendry/aurelia-highcharts#2]
Hi Philip,

Thanks a lot for sharing this sample project and your blog post! I followed up on everything you mentioned, but now I get an error instantiating the ChartCustomElement:

`inner error: ReferenceError: Highcharts is not defined`

I installed highcharts via the October update and made sure that all files are there. I'm quite new to aurelia and not a super expert in js, so there might be something obvious I'm missing, but I can't make it work so far. Any help is much appreciated!

Cheers,

Vincent

**Comment by vincentleeuwen** [comment]
@philiphendry Found it, there was a small typo in charts.js. My bet!

**Comment by philiphendry** [comment]
Awesome. Apologies for not responding sooner but I've been away on Christmas holidays.
