### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by jasonhjohnson** [philiphendry/aurelia-highcharts#3]
Hi,

Just curious if you've enhanced this project at all in the last year?

Thanks,
Jason

**Comment by philiphendry** [comment]
Hi Jason,

I'm afraid this is as far as I've got on this. Whilst I'm integrating Aurelia into our project (on a part-time basis too :( ) the dashboard that has highcharts is written in Angular 1.x and will be replaced with the Aurelia version at a later date. You did bring to my attention the fact that the link to my blog post was broken so I've fixed that at least!
